version: '3'

services:
  php:
    image: fp064-p2-i-php
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    environment:
      - TZ=Europe/Madrid

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Login
      MYSQL_DATABASE: LoginP2
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql

name: fp064-p2
